#!/usr/bin/env bash

procids=()

# Call other gather scripts in parallel
gather_namespaced_resources &
procids+=($!)

gather_clusterscoped_resources &
procids+=($!)

gather_noobaa_resources &
procids+=($!)

gather_ceph_logs &
procids+=($!)

gather_ceph_pod_logs &
procids+=($!)

gather_dr_resources &
procids+=($!)

gather_odf_client &
procids+=($!)

# Check if procid array has any values, if so, wait for them to finish
if [ ${#procids[@]} -ne 0 ]; then
    echo "Waiting on collection scripts to finish."
    wait "${procids[@]}"
fi
