#!/usr/bin/env bash

# Expect base collection path as an exported variable
# If it is not defined, use PWD instead
BASE_COLLECTION_PATH=${BASE_COLLECTION_PATH:-"$(pwd)"}

# Get all namespaces
NAMESPACES=$(oc get namespace | awk '{print $1}')

# Items to check for
NAMESPACE_DR_SYSTEM="openshift-dr-system"
NAMESPACE_OPERATORS="openshift-operators"

# Check if item1 exists in the output
if [[ $NAMESPACES =~ $NAMESPACE_DR_SYSTEM ]]; then
    NAMESPACE=$NAMESPACE_DR_SYSTEM
elif [[ $NAMESPACES =~ $NAMESPACE_OPERATORS ]]; then
    NAMESPACE=$NAMESPACE_OPERATORS
else
    echo "Neither $NAMESPACE_DR_SYSTEM nor $NAMESPACE_OPERATORS exists in the namespaces"
    exit 0
fi

#collect openshift-dr-system namespaced resources
dr_resources=()
dr_resources+=(secrets)
dr_resources+=(configmap)
dr_resources+=(pods -owide)

dbglog "collecting dump of openshift-dr-system namespace"
{ oc adm inspect --dest-dir="${BASE_COLLECTION_PATH}" ns/"${NAMESPACE}" 2>&1; } | dbglog

# Create the dir for oc_output for openshift-dr-system namespace
mkdir -p "${BASE_COLLECTION_PATH}/namespaces/${NAMESPACE}/oc_output/"

# Run the Collection of Resources to list
for dr_resource in "${dr_resources[@]}"; do
    dbglog "collecting oc command ${dr-resource}"
    COMMAND_OUTPUT_FILE=${BASE_COLLECTION_PATH}/namespaces/${NAMESPACE}/oc_output/${dr_resource// /_}
    # shellcheck disable=SC2086
    { oc get ${dr_resource} -n ${NAMESPACE}; } >>"${COMMAND_OUTPUT_FILE}"
done
# Run collection of oc describe command for config map
dbglog "collecting oc describe configmap -n ${NAMESPACE}"
COMMAND_OUTPUT_FILE=${BASE_COLLECTION_PATH}/namespaces/${NAMESPACE}/oc_output/desc_configmap
# shellcheck disable=SC2086
{ oc describe configmap -n ${NAMESPACE}; } >>"${COMMAND_OUTPUT_FILE}"
