#!/usr/bin/env bash

# Expect base collection path as an exported variable
# If it is not defined, use PWD instead
BASE_COLLECTION_PATH=${BASE_COLLECTION_PATH:-"$(pwd)"}

CEPH_COLLECTION_PATH="${BASE_COLLECTION_PATH}/ceph"

# common Ceph resources
common_ceph_resources=()
common_ceph_resources+=(cephobjectstores)
common_ceph_resources+=(cephobjectstoreusers)
common_ceph_resources+=(cephclusters)

for resource in "${common_ceph_resources[@]}"; do
    dbglog "collecting dump ${resource}"
    { oc adm inspect --dest-dir="${CEPH_COLLECTION_PATH}" --all-namespaces ${LOG_FILTER_ARGS:+"${LOG_FILTER_ARGS}"} "${resource}" 2>&1; } | dbglog
done
